### ISSUE TITLE
User Story 11: Log In

### ISSUE THREAD

**Issue by constxd** [constxd/3130project#7]
As a student, I want to be able to log in to my account so I can access the courses I am registered for.
| | Description |
| ------------- | ------------- |
| **ID**  | US:11 |
| **As A**  | Student |
| **I Want** | To be able to log in to my account |
| **So That**  | I can access the courses I am registered for |

**Comment by PeterQLee** [comment]
TODO: make sure that a proper error message is shown when disconnected from internet
